#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# register:
#     path: /register
#     controller: App\Controller\AuthController::register
#     methods: POST

api_login_check:
    path: /api/login_check
    # On dirait que sa à supprimer l'erreur : Unable to find the controller for path "/api/login_check". The route is wrongly configured.
    # controller: App\Controller\Api\V1\UserController::login


